/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myhabittracker;

import java.awt.Color;

/**
 *
 * @author asus
 */
public class addHabit extends javax.swing.JFrame {

    private YesNoJFrame YesNoWindow;
    private MeasurableJFrame setMeasurableWindow;
    private Reminder existingReminder;
    private final DashboardHabit dashboard;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addHabit.class.getName());
    private static final Color FRAME_COLOR = DashboardHabit.FRAME_COLOR;
    private static final Color BUTTON_COLOR = DashboardHabit.BUTTON_COLOR;
    /**
     * Creates new form OptionPanel
     *
     * @param dashboard
     */
    public addHabit(DashboardHabit dashboard) {
        initComponents();
        this.dashboard = dashboard;   // ✅ correctly link dashboard
        setSize(getPreferredSize());   // use the size you set in Designer
        setLocationRelativeTo(null);   // center on screen
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        applyColors();
    }
    
    private void applyColors() {
        getContentPane().setBackground(FRAME_COLOR);
        jPanel1.setBackground(FRAME_COLOR);
        yesNobutton.setBackground(BUTTON_COLOR);
        measurableButton.setBackground(BUTTON_COLOR);
    }
    
    public void openYesNoJFrame() {
        if (YesNoWindow == null || !YesNoWindow.isShowing()) {
            YesNoWindow = new YesNoJFrame(dashboard);
            YesNoWindow.setVisible(true);
        } else {
            YesNoWindow.toFront();
            YesNoWindow.requestFocus();
        }

        this.dispose();
    }

    public void openMeasurableJFrame() {
        if (setMeasurableWindow == null || !setMeasurableWindow.isShowing()) {
            setMeasurableWindow = new MeasurableJFrame(dashboard, existingReminder);
            setMeasurableWindow.setVisible(true);
        } else {
            setMeasurableWindow.toFront();
            setMeasurableWindow.requestFocus(); // ✅ correct
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yesNobutton = new javax.swing.JButton();
        measurableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yesNobutton.setText("Yes/No");
        yesNobutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        yesNobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesNobuttonActionPerformed(evt);
            }
        });

        measurableButton.setText("Measurable");
        measurableButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        measurableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                measurableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(measurableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(yesNobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yesNobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(measurableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesNobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesNobuttonActionPerformed
        // TODO add your handling code here:
        openYesNoJFrame();
    }//GEN-LAST:event_yesNobuttonActionPerformed

    private void measurableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_measurableButtonActionPerformed
        // TODO add your handling code here:
        openMeasurableJFrame();
    }//GEN-LAST:event_measurableButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            DashboardHabit dashboard = new DashboardHabit(); // main dashboard
            dashboard.setVisible(true);
            addHabit adder = new addHabit(dashboard);
            adder.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton measurableButton;
    private javax.swing.JButton yesNobutton;
    // End of variables declaration//GEN-END:variables
}
